version: "3.3"  # optional since v1.27.0

services:
  # MODEL CONTAINER 1
  web_a:
    build:
      context: .
    ports:
      - "7004:8081"
    volumes:
      - ./logvolume01:/var/log
  
  # MODEL CONTAINER 2
  web_b:
    build:
      context: .
    ports:
      - "7005:8081"
    volumes:
      - ./logvolume02:/var/log
volumes:
  logvolume01: {}